# LOOPS

In [46]:
fruits = ['Apple','banana','chiku','kiwi']


#### for loop

In [47]:
for fruit in fruits:
    print(fruit)

Apple
banana
chiku
kiwi


In [48]:
for n in range(11):
    print(n)


0
1
2
3
4
5
6
7
8
9
10


In [49]:
for a in "Advaith":
    print(a)

A
d
v
a
i
t
h


#### while loop

In [50]:
count=0
while count<5:
    print(count)
    count+=1

0
1
2
3
4


In [51]:
count=0
while count<=9:
    print("Advaith")
    count+=1

Advaith
Advaith
Advaith
Advaith
Advaith
Advaith
Advaith
Advaith
Advaith
Advaith


#### control statements

#### if else

In [52]:
n = 4
if n>5:
    print("n is greater")
else:
    print("n is smaller")

n is smaller


#### if else ladder

In [53]:
n = 3
if n>5:
    print("n is greater")
elif n==5:
    print("n is 5")
else:
    print("n is smaller")

n is smaller


In [54]:
def check_even_odd():
    n = 6
    if n % 2 == 0:
        print("n is even")
    else:
        print("n is odd")
check_even_odd()

n is even


In [55]:
def check_even_odd1(a):
    if a % 2 == 0:
        print(a,"is even")
    else:
        print(a,"is odd")
check_even_odd1(3)

3 is odd


In [56]:
for n in range(1,11):
    if n % 2 == 0:
        print(n)
    n+=1

2
4
6
8
10


In [57]:
def even(a,b):
    for n in range(a,b):
        if n % 2 == 0:
            print(n)
        n+=1
even(11,21)

12
14
16
18
20


#### break statement

In [58]:
cnt = 0
while cnt<5:
    if cnt == 4:
        break
    print(cnt)
    cnt+=1
    

0
1
2
3


#### continue statement

In [59]:
cnt1 = 0 
while cnt1<5:
    cnt1+=1
    if cnt1==3:
        continue
    print(cnt1)

1
2
4
5


In [60]:
for i in range(11):
    if i == 5:
        continue
    print(i)

0
1
2
3
4
6
7
8
9
10


In [61]:
def prime(a):
    if a == 0 or a == 1:
        print(a,"is not a prime no")
    elif a>1:
        for i in range(2,a):
            if a % i == 0:
                print(a,"is not a prime no")
                break
        else:
             print(a,"is a prime no")
    else:
        print(a,"is not a prime no")
prime(59)

59 is a prime no


# NUMPY

In [62]:
import numpy as np


In [63]:
Array = np.array([1,2,3,4])
print(Array)

[1 2 3 4]


In [64]:
dArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(dArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### To find out shape of an array

In [65]:
print(dArray.shape)


(3, 3)


#### to find out the dimension of an array

In [66]:
print(dArray.ndim)

2


#### to find out the data type of an array

In [67]:
print(dArray.dtype)

int64


#### to find out the size of an array

In [68]:
print(dArray.size)

9


In [69]:
arr = np.array([10,20,30,40,50])

#### Access single element from an array

In [70]:
print(arr[2])

30


#### Slicing of an array

In [71]:
print(arr[1:4])

[20 30 40]


#### To update the existing array

In [72]:
arr[4]=45
print(arr)

[10 20 30 40 45]


In [73]:
arr = np.array([10,20,30,40,50])
arr[4]=50
print(arr)

[10 20 30 40 50]


#### to access an single element from multi-dimentional array

In [74]:
print(dArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
print(dArray[0,1])

2


In [76]:
print(dArray[2:3])

[[7 8 9]]


#### first 2 columns

In [77]:
print(dArray[:,:2])

[[1 2]
 [4 5]
 [7 8]]


#### first 2 rows

In [78]:
print(dArray[:2])

[[1 2 3]
 [4 5 6]]


#### addition of array

In [79]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


#### substraction of array

In [80]:
print(arr1-arr2)
print(arr2-arr1)

[-3 -3 -3]
[3 3 3]


#### multiplication of array

In [81]:
print(arr1*arr2)

[ 4 10 18]


#### division of array

In [82]:
arr3 = np.array([4,8,12])
arr4 = np.array([2,4,6])
print(arr4/arr3)

[0.5 0.5 0.5]


#### whether the given no is even or odd in array 

In [83]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
for number in numbers:
    if number % 2 == 0:
        print(number,"is Even")
    else:
        print(number,"is Odd")

1 is Odd
2 is Even
3 is Odd
4 is Even
5 is Odd
6 is Even
7 is Odd
8 is Even
9 is Odd
10 is Even


# numpy functions

#### 1. sum

In [84]:
sum = np.array([1,2,3,4,5])
fruits = np.array(["apple","mango","chiku"])
print(sum.sum())

15


#### 2. mean

In [85]:
print(sum.mean())

3.0


#### 3. max

In [86]:
print(sum.max())

5


#### 4. min

In [87]:
print(sum.min())

1


#### 5. standard deviation

In [88]:
print(sum.std())

1.4142135623730951


#### 6. Sorting an array

In [89]:
unsorted_array = np.array([8,12,6,3,90,32])

In [90]:
print(np.sort(unsorted_array))

[ 3  6  8 12 32 90]
